### PR TITLE
Update policy.md

### PR DESCRIPTION
**Pull request by epicfaace**
Fix typo 18-F to 18F

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]

**Comment by dv4harr10** [comment]
Hi Team, I have 3 issues on epicfaace: patch-1 branch I need to have confirmed before proceeding with approval: 1) CODEOWNERS file returns message 'contains errors'. 2) Two README files appear to be incomplete at: development-guide/dev-envs/README.md and development-guide/ethos/README.md. 3) Also, please confirm the content of these 2 files is accurate: requirements-test.txt and requirements.txt. Thanks

**Comment by jsf9k** [comment]
> Hi Team, I have 3 issues on epicfaace: patch-1 branch I need to have confirmed before proceeding with approval: 1) CODEOWNERS file returns message 'contains errors'. 2) Two README files appear to be incomplete at: development-guide/dev-envs/README.md and development-guide/ethos/README.md. 3) Also, please confirm the content of these 2 files is accurate: requirements-test.txt and requirements.txt. Thanks

1. Can you share a link showing where you are seeing the error in the codeowners file?
2. The incompleteness of `development-guide/dev-envs/README.md` and `development-guide/ethos/README.md` are unrelated to this PR.  You should create an issue in this repo for that.
3. The files `requirements-test.txt` and `requirements.txt` look correct to me.

**Comment by dv4harr10** [comment]
Please see attached CODEOWNERS file.

CODEOWNERS_91223

**Review by mcdonnnj — APPROVED** [review]
LGTM ✔

**Comment by dv4harr10** [comment]
Hi Shane, Please confirm if the README files need the separate PR in your opinion ? Or if they look ok. Thanks

**Comment by jsf9k** [comment]
> Please see attached CODEOWNERS file.
> 
> CODEOWNERS_91223

This is because you're looking at the fork, not the original repo.

**Comment by dv4harr10** [comment]
Ok Thanks for confirming it's a non-issue.

**Pull request merged**
