### PR TITLE
Lineage pull request for: skeleton

### PR DESCRIPTION
**Pull request by cisagovbot**
# Lineage Pull Request #

[Lineage] has created this pull request to incorporate new changes found in an
upstream repository:

Upstream repository: [`https://github.com/cisagov/skeleton-generic.git`](https://github.com/cisagov/skeleton-generic.git)
Remote branch: `HEAD`

Check the changes in this pull request to ensure they won't cause issues with
your project.

------------

**Note:** *You are seeing this because one of this repository's maintainers has
configured [Lineage] to open pull requests.*

For more information:

🛠 [Lineage] configurations for this project are stored in `.github/lineage.yml`

📚 [Read more about Lineage][Lineage]

[//]: # (lineage:metadata:{&quot;slayed&quot;:true})
[Lineage]: https://github.com/cisagov/action-lineage/ "Lineage GitHub Action"

### CODE REVIEW

**Comment by jsf9k** [comment]
@mcdonnnj, do you know how to fix the remaining `mypy` issues?

**Comment by mcdonnnj** [comment]
> 
> 
> @mcdonnnj, do you know how to fix the remaining `mypy` issues?

@jsf9k In `0.900` [mypy switched to a modular stubs model](https://mypy-lang.blogspot.com/2021/05/the-upcoming-switch-to-modular-typeshed.html) and because the `mypy` hook runs in a venv we must provide the missing stubs as additional dependencies. It adds some overhead, but should be straightforward to maintain.

**Comment by jsf9k** [comment]
> > @mcdonnnj, do you know how to fix the remaining `mypy` issues?
> 
> @jsf9k In `0.900` [mypy switched to a modular stubs model](https://mypy-lang.blogspot.com/2021/05/the-upcoming-switch-to-modular-typeshed.html) and because the `mypy` hook runs in a venv we must provide the missing stubs as additional dependencies. It adds some overhead, but should be straightforward to maintain.

Right.  I tried adding them to `extras_require.test` in `setup.py` locally yesterday, then re-running `pip install -r requirements-dev.txt` and `pre-commit run -a` but no dice; I thought there must be more to the story.

**Comment by jsf9k** [comment]
> > > @mcdonnnj, do you know how to fix the remaining `mypy` issues?
> > 
> > 
> > @jsf9k In `0.900` [mypy switched to a modular stubs model](https://mypy-lang.blogspot.com/2021/05/the-upcoming-switch-to-modular-typeshed.html) and because the `mypy` hook runs in a venv we must provide the missing stubs as additional dependencies. It adds some overhead, but should be straightforward to maintain.
> 
> Right. I tried adding them to `extras_require.test` in `setup.py` locally yesterday, then re-running `pip install -r requirements-dev.txt` and `pre-commit run -a` but no dice; I thought there must be more to the story.

Ah, now I see cisagov/skeleton-python-library@77c19cb1c5a43e0f100f04caaaa913e8baaab9de and this makes more sense.

**Review by jsf9k — APPROVED** [review]
Thanks for sorting out `mypy`, @mcdonnnj!

**Review by dav3r — APPROVED** [review]
👍

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Pull request merged**
